module.exports = {
  urlStub: 'https://api.trello.com/1',
  defaults: {
    boardDefaultLabels: false,
    boardDefaultLists: false,
    boardDescription: 'this board was created by TAAB (see https://www.npmjs.com/package/taab)',
    boardKeepFromSource: 'all',
    boardName: '[taab] new board',
    backgroundColor: 'grey',
    cardDescription: 'this card was created by TAAB (see https://www.npmjs.com/package/taab)',
    cardName: '[taab] new card',
    cardPos: 'top',
    cardActions: 'all',
    cardAttachmnet: true,
    cardAttachmentFields: 'all',
    cardStickers: true,
    cardMembers: true,
    cardMemberFields: 'all',
    cardCheckItemStates: true,
    cardChecklists: 'all',
    cardLimit: 100, // 1- 1000
    cardSince: null,
    cardBefore: null,
    cardFilter: 'visible',
    cardFields: 'all',
    listName: '[taab] new list',
  },
};
